on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak Builder"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v5
      with:
        bundle: "flatseal-dev.flatpak"
        manifest-path: "com.github.tchx84.Flatseal.json"
        run-tests: "true"